version: '3.4'

services:
  app-consumer:
    tty: true
    build: ./consumer
    depends_on:
      - kafka
      - mongodb_candles
    volumes:
      # - /home/node/app/consumer
      - ./consumer/:/home/node/app/consumer/
    ports:
      - 5000:5000
    links:
      - kafka
      - mongodb_candles

  app-producer:
    tty: true
    build: ./producer
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      # - /home/node/app/producer
      - ./producer:/home/node/app/producer/
    ports:
      - 3000:3000
    links:
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10

  kafkaui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  mongodb_candles:
    image: 'mongo:latest'
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/da

volumes:
  mongodb_data_container: